package pusu

import "log/slog"

// MsgID is the type of the message id, the unique message number associated
// with each message from the client
type MsgID int64

// NoMsgID is a canonical value for a message ID that doesn't relate to a
// message. In practice any value less than zero is not generated by the pusu
// client.
const NoMsgID = MsgID(-1)

const msgIDAttrName = AttrPfx + "MsgID"

// Attr returns a slog.Attr describing the message id
func (i MsgID) Attr() slog.Attr {
	if i < 0 {
		return slog.String(msgIDAttrName, "Unknown")
	}

	return slog.Int64(msgIDAttrName, int64(i))
}
