// Code generated by "stringer -type MsgType"; DO NOT EDIT.

package pusu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MinMsgType-0]
	_ = x[Identify-1]
	_ = x[Publish-2]
	_ = x[Subscribe-3]
	_ = x[Unsubscribe-4]
	_ = x[UnsubscribeAll-5]
	_ = x[Ping-6]
	_ = x[MaxMsgType-7]
}

const _MsgType_name = "MinMsgTypeIdentifyPublishSubscribeUnsubscribeUnsubscribeAllPingMaxMsgType"

var _MsgType_index = [...]uint8{0, 10, 18, 25, 34, 45, 59, 63, 73}

func (i MsgType) String() string {
	if i >= MsgType(len(_MsgType_index)-1) {
		return "MsgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MsgType_name[_MsgType_index[i]:_MsgType_index[i+1]]
}
