// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pusu.proto

package pusu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubscriptionMsgPayload is the message used to send subscriptions and
// unsubscriptions to the pub/sub server.
type SubscriptionMsgPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the collection of subscriptions
	Subs          []*SubscriptionMsgPayload_Sub `protobuf:"bytes,1,rep,name=subs,proto3" json:"subs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionMsgPayload) Reset() {
	*x = SubscriptionMsgPayload{}
	mi := &file_pusu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionMsgPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionMsgPayload) ProtoMessage() {}

func (x *SubscriptionMsgPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pusu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionMsgPayload.ProtoReflect.Descriptor instead.
func (*SubscriptionMsgPayload) Descriptor() ([]byte, []int) {
	return file_pusu_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptionMsgPayload) GetSubs() []*SubscriptionMsgPayload_Sub {
	if x != nil {
		return x.Subs
	}
	return nil
}

// PublishMsgPayload is the message used to publish data on a topic
type PublishMsgPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the topic on which to publish
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// the data being published
	Payload       []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMsgPayload) Reset() {
	*x = PublishMsgPayload{}
	mi := &file_pusu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMsgPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMsgPayload) ProtoMessage() {}

func (x *PublishMsgPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pusu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMsgPayload.ProtoReflect.Descriptor instead.
func (*PublishMsgPayload) Descriptor() ([]byte, []int) {
	return file_pusu_proto_rawDescGZIP(), []int{1}
}

func (x *PublishMsgPayload) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishMsgPayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// PingMsgPayload is the message used to request a Ping response from the
// server. It is returned, unchanged, to the client.
type PingMsgPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the time the ping was requested
	PingTime      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=pingTime,proto3" json:"pingTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingMsgPayload) Reset() {
	*x = PingMsgPayload{}
	mi := &file_pusu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingMsgPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMsgPayload) ProtoMessage() {}

func (x *PingMsgPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pusu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMsgPayload.ProtoReflect.Descriptor instead.
func (*PingMsgPayload) Descriptor() ([]byte, []int) {
	return file_pusu_proto_rawDescGZIP(), []int{2}
}

func (x *PingMsgPayload) GetPingTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PingTime
	}
	return nil
}

type SubscriptionMsgPayload_Sub struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the topic to subscribe to
	Topic         string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionMsgPayload_Sub) Reset() {
	*x = SubscriptionMsgPayload_Sub{}
	mi := &file_pusu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionMsgPayload_Sub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionMsgPayload_Sub) ProtoMessage() {}

func (x *SubscriptionMsgPayload_Sub) ProtoReflect() protoreflect.Message {
	mi := &file_pusu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionMsgPayload_Sub.ProtoReflect.Descriptor instead.
func (*SubscriptionMsgPayload_Sub) Descriptor() ([]byte, []int) {
	return file_pusu_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SubscriptionMsgPayload_Sub) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

var File_pusu_proto protoreflect.FileDescriptor

const file_pusu_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"pusu.proto\x12\x04pusu\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n" +
	"\x16SubscriptionMsgPayload\x124\n" +
	"\x04subs\x18\x01 \x03(\v2 .pusu.SubscriptionMsgPayload.SubR\x04subs\x1a\x1b\n" +
	"\x03Sub\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"C\n" +
	"\x11PublishMsgPayload\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"H\n" +
	"\x0ePingMsgPayload\x126\n" +
	"\bpingTime\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bpingTimeB$Z\"github.com/nickwells/pusu.mod/pusub\x06proto3"

var (
	file_pusu_proto_rawDescOnce sync.Once
	file_pusu_proto_rawDescData []byte
)

func file_pusu_proto_rawDescGZIP() []byte {
	file_pusu_proto_rawDescOnce.Do(func() {
		file_pusu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pusu_proto_rawDesc), len(file_pusu_proto_rawDesc)))
	})
	return file_pusu_proto_rawDescData
}

var file_pusu_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pusu_proto_goTypes = []any{
	(*SubscriptionMsgPayload)(nil),     // 0: pusu.SubscriptionMsgPayload
	(*PublishMsgPayload)(nil),          // 1: pusu.PublishMsgPayload
	(*PingMsgPayload)(nil),             // 2: pusu.PingMsgPayload
	(*SubscriptionMsgPayload_Sub)(nil), // 3: pusu.SubscriptionMsgPayload.Sub
	(*timestamppb.Timestamp)(nil),      // 4: google.protobuf.Timestamp
}
var file_pusu_proto_depIdxs = []int32{
	3, // 0: pusu.SubscriptionMsgPayload.subs:type_name -> pusu.SubscriptionMsgPayload.Sub
	4, // 1: pusu.PingMsgPayload.pingTime:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pusu_proto_init() }
func file_pusu_proto_init() {
	if File_pusu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pusu_proto_rawDesc), len(file_pusu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pusu_proto_goTypes,
		DependencyIndexes: file_pusu_proto_depIdxs,
		MessageInfos:      file_pusu_proto_msgTypes,
	}.Build()
	File_pusu_proto = out.File
	file_pusu_proto_goTypes = nil
	file_pusu_proto_depIdxs = nil
}
